### ISSUE TITLE
Dodavanje regionalnog menadzera - nepotpuna validacija

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#12]
Komponenta:
RegMenadzerDodajIzmjeniGUI.java

commit ID:
21d0b75

Opis problema:
Omogucen unos jednocifrenog telefona, kao i jednoslovnih imena i prezimena.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Otvoriti tab "Regionalni menadzeri" te kliknuti Dodaj.
3. Unijeti redom u polja (i, p, 0,a,  a@bb.cc, //).

Dobijeni rezultat(respektivno):
http://pokit.org/get/?dc8207339976031dd0212e88aac0ba8c.jpg

Očekivani rezultat:
Onemoguceno dodavanje imena, prezimena koja imaju jedno slovo, kao i telefon 1 cifre.

**Comment by AmarPanjeta** [comment]
Popravljeno
