### ISSUE TITLE
Pogresna validacija - onemogucen unos imena ili prezimena od 2 rijeci za prodavaca

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#15]
Komponenta:
DodavanjeProizvodaGUI.java

commit ID:
36b9856

Opis problema:
Omogucen unos jednocifrenog telefona, kao i onemogucena imena i prezimena od 2 rijeci.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Otvoriti tab "Proizvodi" te kliknuti Dodaj.
3. Unijeti redom u polja (Ana Marija, Van Damme, 0, a, a@bb.cc, //, //).

Dobijeni rezulta:
http://pokit.org/get/?3ade37a25fe6c6effb4d2eea47c843ba.jpg

Očekivani rezultat:
Omoguceno dodavanje imena i prezimena koja imaju 2 rijeci.

**Comment by apalavra1** [comment]
Pretpostavljeno je da će se unositi samo ime i prezime (bez razmaka) što kaže i validacija.
