### ISSUE TITLE
Exception pri unosu cijene pri dodaji nabavke

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#17]
Komponenta:
DodavanjeProizvodaGUI.java

commit ID:
36b9856

Opis problema:
Nije ogranicen unos cijene, sto za velike brojeve izaziva exception.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Otvoriti tab "Prozivod" te kliknuti Dodaj.
3. Unijeti redom u polja ("haha", 99999999999999999999999999999, 99999999999999999999, 99).

Dobijeni rezultat:
http://pokit.org/get/?053d291e4af68fe3cc43e4eaea23b1de.jpg

Očekivani rezultat:
Onemogucen unos apsurdno velikih cijena.

**Comment by AmarPanjeta** [comment]
Za dati commit nismo mogli replicirati bug, tako da cemo ovo morati oznaciti kao invalid. 

Takodjer, postoje dvije napomene:
1. Dostavljeni podaci nisu validni, tako da se ovaj proizvod ne bi mogao spasiti(slika ispod)
http://pokit.org/get/?2119ecca2fa085ecef86c8bf36736d84.jpg
2. Za podatke gdje je prodajna cijena veca od nabavne, ne desi se exception(rezultat na slici ispod)
http://pokit.org/get/?600c120bdc4ccb1af2aeb22d70d30604.jpg

**Comment by ncorovic1** [comment]
Da greska je, treba zamijeniti prodajnu i nabavnu cijenu. A sto se tice samog iznosa treba unijeti jos 9ki da bi se presla granica za Integer. Ja sam malo skratio iznos pri prijavi greske. Tako da trebali bi kucati nesto ovog tipa:
Nabavna cijena: 99999999999999999999999999999999999999999999999999999999999999999999999999999988
Prodajna cijena: 99999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by AmarPanjeta** [comment]
Revizijom smo dosli do zakljucka da je ovo ipak bug, koji je popravljen u kasnijem commitu
