### ISSUE TITLE
Nepostojanje validacije drzave pri dodavanju regiona

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#18]
Komponenta:
DodavanjeRegijeGUI.java

commit ID:
36b9856

Opis problema:
Nepostojanje validacije drzave pri dodavanju regiona.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Otvoriti tab "Regije" te kliknuti Dodaj.
3. Unijeti redom u polja ("imeRegije", "tutiFruti").

Dobijeni rezultat:
http://pokit.org/get/?143210557c3f6ab9d997ad52f13af1ef.jpg

Očekivani rezultat:
Onemogucen unos nepostojece drzave.

**Comment by encore13** [comment]
Neke teritorije se odcjepljuju kolega pa se tako formiraju nove države. Ko zna, možda se neka bude baš zvala tuti fruti :)))
Evo da mi se malo opustiš https://www.youtube.com/watch?v=cyqX0mwu0PI :D

**Comment by ncorovic1** [comment]
Hahaha posteno kolega. :D
