### ISSUE TITLE
Neusaglašenost SRS-a i koda (Validacija forme ŠefProdaje)

### ISSUE THREAD

**Issue by adnatahic** [SoftverInzenjeringETFSA/SI2015Tim8#19]
Komponenta: SefProdajeMainGUI.java
commit ID: 6ce6598c673316e6419b13369a3a494a94313329
Opis problema: Kada ste logovani kao šef prodaje,klikom na tab Proizvodi, zatim na button Dodaj, omogući se unos novog proizvoda. Omogućen je unos nabavne cijene 0, iako u SRS-u je naglašeno da je nabavna cijena pozitivan broj.
Koraci za reproduciranje problema:
1.  Pokrenuti desktop aplikaciju Mlmarketing.
2.  Logovati se kao šef prodaje (username: master, password: master)
3.  Odlazak na tab Proizvodi
4.  Klik na button Dodaj
5.  Unos podataka, kao i nabavne cijene 0
6.  Potvrda

Dobijeni rezultat: Kreira se proizvod sa nabavnom cijenom 0:. http://prntscr.com/b4xsrw
Očekivani rezultat: Obavijest, odnosno nemogućnost kreiranja proizvoda sa nabavnom cijenom 0.

**Comment by AmarPanjeta** [comment]
Popravljeno
