### ISSUE TITLE
Izmjene Proizvoda

### ISSUE THREAD

**Issue by adnatahic** [SoftverInzenjeringETFSA/SI2015Tim8#20]
Komponenta: SefProdajeMainGUI.java
commit ID: 6ce6598c673316e6419b13369a3a494a94313329
Opis problema: Kada ste logovani kao šef prodaje,klikom na tab Proizvodi, zatim na button Izmijeni, omogući se promjena podataka o željenom proizvodu. Međutim, nije moguće izvršiti samo izmjenu cijene ili stanja u skladištu. Ako se ne promijeni naziv proizvoda, dobije se obavijest o postojanju istoimenog proizvoda u bazi.

Koraci za reproduciranje problema:
1.  Pokrenuti desktop aplikaciju Mlmarketing.
2.  Logovati se kao šef prodaje (username: master, password: master)
3.  Odlazak na tab Proizvodi
4.  Klik na button Izmijeni
5.  Izmjena bilo kojeg polja, osim naziva proizvoda
6.  Izmijeni

Dobijeni rezultat: http://prntscr.com/b4y2h0
Očekivani rezultat: Mogućnost izmjene podataka o proizvodu, bez promjene imena proizvoda.

**Comment by AmarPanjeta** [comment]
Popravljeno
