### ISSUE TITLE
Exception pri izmjeni proizvoda

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#21]
Komponenta:
IzmjenaProizvodaGUI.java

commit ID:
36b9856

Opis problema:
Mogucnost izmjene proizvoda koji se ne nalazi u bazi.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Otvoriti tab "Proizvodi" te kliknuti Dodaj.
3. Unijeti redom u polja (P1, 1, 2, 3).
4. Kliknuti na dodani proizvod i na izmjenu.
5. Vratiti se na tab Proizvodi, bez zatvaranja forme za izmjenu, te kliknuti na obrisi.
6. Vratiti se na otvorenu formu za izmjenu i kliknuti Izmijeni proizvod i potvrditi sa Da.

Dobijeni rezultat:
http://pokit.org/get/?23fcaaad5b82205aaf517935ddd7e3d4.jpg

Očekivani rezultat:
Onemoguceno brisanje nepostojecih proizvoda.

**Comment by AmarPanjeta** [comment]
Popravljeno
