### ISSUE TITLE
Neusaglašenost SRS-a i koda - Login/Logout

### ISSUE THREAD

**Issue by adnatahic** [SoftverInzenjeringETFSA/SI2015Tim8#22]
Komponenta: LoginGUI.java
commit ID: 0ee27cf40150a6b07e392fe94ddf70728057c79f
Opis problema: Kada se želimo logovati na sistem sa neispravnim podacima, ne dobija se obavijest, iako je u SRS-u naglašeno da će je biti : http://prntscr.com/b5cmxa

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju Mlmarketing.
2. Unijeti neispravne login podatke
3. Prijava

Dobijeni rezultat: Ništa se ne desi.
Očekivani rezultat: Obavijest da login podaci nisu ispravni.

---

Komponenta: SefProdajeMainGUI.java
commit ID: 6ce6598c673316e6419b13369a3a494a94313329
Opis problema: Kada se želimo izlogovati sa sistema, ne prikaže se obavijest o uspješnoj odjavi, iako je u SRS-u naglašeno da će je biti : http://prntscr.com/b5cqwb

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju Mlmarketing.
2. Unijeti ispravne login podatke
3. Prijava
4. Klik na button Odjava sa sistema

Dobijeni rezultat: Ništa se ne desi.
Očekivani rezultat: Obavijest o uspješnoj odjavi

**Comment by AmarPanjeta** [comment]
Popravljeno
