### ISSUE TITLE
Mogućnost naručivanja proizvoda kojeg nema dovoljno na skladištu

### ISSUE THREAD

**Issue by MerisaGolic** [SoftverInzenjeringETFSA/SI2015Tim8#25]
Komponenta:
Komercijalista - Narudžbe

Commit id:
59046b744d687af9154c0ad647c4444f8d977cf6

Opis:
Na narudžbi se može unijeti količina proizvoda veća od one u skladištu.

Koraci za reproduciranje problema:
1.Pokrenuti App.java
2.Login kao master 
3.Dodati zaposlenika komercijalistu
4.Dodati prozvod
5.Logout kao master
6.Login kao komercijalista
7.Klik na tab Narudžbe, pa na button Dodaj
8.Izabrati proizvod iz liste, i unijeti količinu veću od one u skladištu
9.Kliknuti button Kreiraj

Dobijeni rezultat:
Narudžba je spremljena u listu narudžbi.
Screenshot:
http://pokit.org/get/?45a4f6ee97ebfa501d5d2507abf5dccc.jpg
http://pokit.org/get/?d0d9e603e2db3726adf0609e08d42298.jpg

Očekivani rezultat:
Nemogućnost unosa količine naručenog proizvoda veće od količine proizvoda u skladištu.
Obavještenje da ne postoji tražena količina proizvoda, te omogućavanje ponovnog unosa količine.

**Comment by apalavra1** [comment]
Može se naručiti proizvod kojeg nema dovoljno na skladištu jer se prije potvrđivanja narudžbe taj isti proizvod može nabaviti. Ne može se potvrditi narudžba za koju nema dovoljne količine nekog od naručenih proizvoda.
