### ISSUE TITLE
Status narudzbi nije validan

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#26]
Komponenta:
SefProdajeMainGUI.java

commit ID:
6ce6598

Opis problema:
Status narudzbe nije update-ovan u tabeli nakon sto je izmijenjen.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Dodati komercijalistu u tabu korisnici, odjaviti se sa korisnickog naloga mastera i prijaviti sa novo napravljenim nalogom komercijaliste.
3. Dodati narudzbu.
4. Odjaviti se sa korisnickog naloga komercijaliste i ponovno prijaviti na nalog master.
5. U tabu narudzbe odabrati dodanu narudzbu, te klikom na izmijeni promijeniti status sa "na 
    cekanju" na "odbijena" i potvrditi.

Dobijeni rezultat:
http://pokit.org/get/?b87deb3c780444885355337214d4e241.jpg

Očekivani rezultat:
Status narudzbe je update-ovan u tabeli nakon poruke "Uspjesno ste promijenili status narudzbe".

**Comment by encore13** [comment]
Duplikat issuea #16 kolegice Adne.
