### ISSUE TITLE
Datum fakture u komercijalisti nije ispravno prikazan

### ISSUE THREAD

**Issue by ncorovic1** [SoftverInzenjeringETFSA/SI2015Tim8#27]
Komponenta:
SefProdajeMainGUI.java

commit ID:
6ce6598

Opis problema:
Datum fakture u komercijalisti nije ispravno prikazan. Ne vidi se ime mjeseca.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Dodati komercijalistu u tabu korisnici, odjaviti se sa korisnickog naloga mastera i prijaviti sa novo
napravljenim nalogom komercijaliste.
3. Dodati narudzbu i fakturisati je klikom na kreiraj fakturu.
4. U tabu fakture kliknuti "Prikazi fakturu".

Dobijeni rezultat:
http://pokit.org/get/?58fc0087a40a7af272c08cb0fcede939.jpg

Očekivani rezultat:
Datum fakture ispravno prikazan.

**Comment by encore13** [comment]
Prepravljen u Adijevom commitu.
