### ISSUE TITLE
Informativne poruke za preostale stavke

### ISSUE THREAD

**Issue by vhrustic** [SoftverInzenjeringETFSA/SI2015Tim8#30]
Komponente:
Prodavači - dodaj, obriši, izmjeni, unaprijed, dodaj nadleznog menađera

Commit id:
e890c1b

Opis problema:
U SRS-u(funkcionalnim zahtjevima) je navedeno da se nakon dodavanja, brisanja, izmjene nekog od Prodavača korisnik obavještava o uspješnosti akcije. Isto važi i za dodijeljivanje nadleznog menadjera i unaprijeđivanje. Također nisu sortirani po abecednom poretku. Isto važi i za preostale tabove; Proizvodi, Regije, itd.

Koraci za reproduciranje problema:
1.LoginGUI
2.Login kao master:master(vođa prodaje)
3.Klinuti na tab Prodavači i unijeti/registrovati nekoliko korisnika za potrebe testiranja
4. Odabrati nekog od prodavača izbrisati ga iz evidencije; Dodati novog prodavača  izmjeniti postojećeg prodavača, Unaprijediti prodavača ili dodijeliti mu nadleznog menađera
Dobijeni rezultat:
Uneseni korisnici nisu sortirani po abecedi ni po jednoj koloni.
Nakon brisanja korisnika, on nestane iz liste, ne dobijemo nikakavu poruku o uspješnosti akcije. Isto važi za dodavanje, editovanje, brisanje, unaprijeđivanj ei dodijeljivanje reg. menađera za svakog prodavača.

Očekivani rezultat:
Sortirani spisak, poruke o uspješnoj akciji za navedene stavke

Write

**Comment by vhrustic** [comment]
Ista greška se pojavljuje i na ostalim tabovima, manje više, da ne bih otvarao svaki za svaku issue.

**Comment by encore13** [comment]
Već jesi otvorio issue za tab regionalnih menadžera  #29 i tab korisnika  #28, sa identičnim problemom al' hajd' :D
