### ISSUE TITLE
Brisanje korisnika i narudžbi nakon perioda neaktivnosti

### ISSUE THREAD

**Issue by vhrustic** [SoftverInzenjeringETFSA/SI2015Tim8#32]
Komponenta:
Automatsko brisanje neaktivnih korisnika, naruđbi

Commit id:
e890c1b

Opis problema:
U SRS-u; NFZ19; Korisnici se brišu automatski nakon što im je račun neaktivan 2 godine. Isto važi iza NFZ20! U specifikaciji softvera-SRS-u ne postoji polje tipa Date ili sl. u koje bi se zapisivao datum i vrijeme posljednje aktivnosti za račun i narudžbe, a bez toga je nemoguće izvesti navedenu funkcionalnost.

Koraci za reproduciranje problema:
1 .Pokrenuti LoginGUI
2. Login kao master:master(vođa prodaje)
3. Kliknuti na tab Korisnici
4. Kreirati novog korisnika
5. Odjaviti se kao master
6. Prijaviti se kao prethodno kreirani korisnik
7. Sačekati 2 godine ^^ 

Dobijeni rezultat:
Nema automatskog brisanja računa koji je 2 godine neaktivan.

Očekivani rezultat:
Automatsko brisanje računa koji je 2 godine neaktivan i narudzbi.

**Comment by AmarPanjeta** [comment]
Onda nema argumenata da ovo tretiramo kao bug.

**Comment by vhrustic** [comment]
Uvidom u dokumentaciju primjetio sam da nigdje ne čuvate u bazi podataka datum posljednje aktivnosti, a bez toga ne vidim kako bi ste to implementirali? Prepravio sam opis bug-a
