### ISSUE TITLE
Exception pri izmjeni regionalnog menadžera

### ISSUE THREAD

**Issue by MerisaGolic** [SoftverInzenjeringETFSA/SI2015Tim8#33]
Komponenta:
RegMenadzerDodajIzmjeniGUI.java

commit ID:
36b9856

Opis problema:
Mogucnost izmjene reginalonog menadzera koji se ne nalazi u bazi.

Koraci za reproduciranje problema:
1. Login kao master (username: master, password: master)
2. Otvoriti tab "Regionalni menadžeri" te kliknuti Dodaj.
3. Popuniti polja ispravno, kliknuti Dodaj.
4. Vratiti se na formu Sef, te kliknuti na dodanog menadzera i na izmjeni.
5. Bez zatvaranja forme za izmjenu, kliknuti na obrisi na tabu "Regionalni menadžeri".
6. Vratiti se na otvorenu formu za izmjenu i kliknuti Izmijeni i potvrditi sa Da.

Dobijeni rezultat:
Unhandled exception

Očekivani rezultat:
Onemogućeno brisanje nepostojećih menadžera.

**Comment by encore13** [comment]
Popravljeno :))
